tier: 'stage'
deletefile: '/media/sf_VMShare/bulkdeletion/DELETE_diagnosis.tsv'
submissionid: 'f465a88d-267d-4f5a-8671-3a5e987c06a7' #One of the Insilicom submissions
node: 'diagnosis'
# Shouldn't need to edit anything below this line
mdffiles:
  CDS:
    - "https://raw.githubusercontent.com/CBIIT/cds-model/refs/heads/{}/model-desc/cds-model.yml"
    - "https://raw.githubusercontent.com/CBIIT/cds-model/refs/heads/{}/model-desc/cds-model-props.yml"
  ICDC:
    - "https://raw.githubusercontent.com/CBIIT/icdc-model-tool/refs/tags/{}/model-desc/icdc-model.yml"
    - "https://raw.githubusercontent.com/CBIIT/icdc-model-tool/refs/tags/{}/model-desc/icdc-model-props.yml"
  CTDC:
    - "https://raw.githubusercontent.com/CBIIT/ctdc-model/refs/tags/{}/model-desc/ctdc_model_file.yaml"
    - "https://raw.githubusercontent.com/CBIIT/ctdc-model/refs/tags/{}/model-desc/ctdc_model_properties_file.yaml"